# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mwhamgenomics.github.io
# email: your-email@domain.com
description: >  # ignore newlines until "baseurl:"
  Biology, programming, music.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mwhamgenomics.github.io" # the base hostname & protocol
# twitter_username: jekyllrb
github_username:  mwhamgenomics

# Build settings
markdown: kramdown
