# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Genomics in B<span class="music">♭</span>
description: >  # ignore newlines until "baseurl:"
  <i class="fa fa-flask"></i> Biology, <i class="fa fa-terminal"></i> programming, <i class="fa fa-music"></i> music.
plain_description: Biology, progamming, music.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mwhamgenomics.github.io" # the base hostname & protocol
github_username:  mwhamgenomics

# Build settings
markdown: kramdown
